### PR TITLE
fix: docker desktop startup failure

### LINKED ISSUE #470: nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:41:18 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:41:19 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:41:19 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:41:20 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:41:20 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:41:21 nginx: [emerg] still could not bind()
2023-05-30 08:42:21 
2023-05-30 08:42:21 WARNING: using fixed Admin API token has security risk.
2023-05-30 08:42:21 Please modify "admin_key" in conf/config.yaml .
2023-05-30 08:42:21 
2023-05-30 08:42:21 
2023-05-30 08:42:22 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:42:22 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:42:23 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:42:23 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:42:24 nginx: [emerg] bind() to unix:/usr/local/apisix/conf/config_listen.sock failed (98: Address already in use)
2023-05-30 08:42:24 nginx: [emerg] still could not bind()

image

### PR DESCRIPTION
**Pull request by season886**
fix #470 #373 in debian

### CODE REVIEW

**Review by lingsamuel — APPROVED** [review]

**Comment by lingsamuel** [comment]
This should be a workable workaround.

File: centos/docker-entrypoint.sh [hunk 1]
```diff
@@ -45,6 +45,10 @@ _EOC_
         /usr/bin/apisix init
         /usr/bin/apisix init_etcd
     fi
+
+    if [ -e "/usr/local/apisix/conf/config_listen.sock" ]; then
```
Comment (monkeyDluffy6017) [inline centos/docker-entrypoint.sh:49]: Could you add a comment: For versions below 3.5.0 whose conf_server has not been removed.

**Review by monkeyDluffy6017 — APPROVED** [review]
